language: julia
notifications:
    email: false
julia:
    - 0.5
    - 0.6
    - 1.0
    - 1.1
    - nightly
#script: # use the default script which is equivalent to the following
#    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#    - julia -e 'Pkg.init(); Pkg.clone(pwd())'
#    - julia -e 'Pkg.test("PortableGameNotation", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("PortableGameNotation")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
